[package]
name = "ddf-oom-example"
version = "0.1.0"
edition = "2021"

[dependencies]
differential-dataflow = "0.12"
timely = { version = "0.12", features = ["bincode"] }
rust_decimal = "1.36"
rust_decimal_macros = "1.36"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
